# A home-manager module for pymux, so `~/.pymux.conf` is generated.
#
# pymux reads that file at startup: one command per line, the same shape as
# `pymux/examples/example-config.conf`. Until now a person who manages the
# rest of their home with Nix had to write and place that one file by hand.
# Lillecarl/pymux#190.
#
# **This is a path, not a flake output.** It is a plain module file, so
#
#     imports = [ /path/to/pyterm/nix/home-manager.nix ];
#
# is the whole import. `default.nix` names it as `homeManagerModules.default`
# and `flake.nix` passes that attribute through. All three routes reach this
# file, and nothing here is reachable only through a flake.
#
# **Two options carry the configuration, and no more.** `settings` writes
# `set-option` lines and `extraConfig` writes everything else. There is no
# typed option per pymux setting, because `pymux/pymux/options.py` already
# names every one of them. A second list here would go stale, and a person
# would have to learn which Nix name means which pymux name. This way
# `settings.prefix = "C-a"` is `set-option prefix C-a`, spelled the way pymux
# spells it.
#
# This module writes only what it is asked for. pymux has its own defaults,
# and repeating them here would make a change to one of them invisible to
# anybody who uses this.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.pymux;

  # pymux splits a line with `shlex.split`
  # (`pymux/pymux/commands/commands.py:87`), so a value that holds a space,
  # a quote or a leading "#" has to arrive quoted. `status-left` is the one
  # that shows it: `'[#h:#S] '` holds a "#", a ":" and a trailing space.
  spell =
    one:
    if lib.isBool one then
      (if one then "on" else "off")
    else if lib.isInt one then
      toString one
    else
      lib.escapeShellArg one;

  # A setting of `null` writes no line at all, so one module can turn off
  # what another set without knowing pymux's own default for it.
  chosen = lib.filterAttrs (_: one: one != null) cfg.settings;

  settingLines = lib.mapAttrsToList (name: one: "set-option ${name} ${spell one}") chosen;

  header = ''
    # Generated by home-manager. Edit the Nix configuration, not this file.
  '';
in
{
  options.programs.pymux = {
    enable = lib.mkEnableOption "pymux, a pure Python terminal multiplexer";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = (import ../. { inherit pkgs; }).pymux;
      defaultText = lib.literalExpression "(import <the pyterm checkout> { inherit pkgs; }).pymux";
      description = ''
        Which pymux to install. pymux is not in nixpkgs, so the default
        builds it from the checkout this module came out of.

        `null` installs nothing and still writes the configuration file,
        for a person who gets pymux from somewhere else.
      '';
    };

    settings = lib.mkOption {
      type =
        with lib.types;
        attrsOf (
          nullOr (oneOf [
            bool
            int
            str
          ])
        );
      default = { };
      example = {
        prefix = "C-a";
        base-index = 1;
        mode-keys = "vi";
        history-limit = 5000;
        mouse = true;
      };
      description = ''
        One `set-option` line for each entry. The names are pymux's own,
        from `pymux/pymux/options.py`.

        `true` and `false` become `on` and `off`, a number becomes
        itself, and a string is quoted. `null` writes no line.

        Nothing here checks a name. pymux reports one it does not know at
        startup, and names the file and the line that said it.
      '';
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = ''
        bind-key "|" split-window -h
        bind-key "-" -- split-window -v
      '';
      description = ''
        Lines added after the settings. Key bindings go here: `bind-key`
        takes a command and its own arguments, and a Nix option cannot
        spell that better than the line itself does.
      '';
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      { home.packages = lib.optional (cfg.package != null) cfg.package; }

      {
        home.file.".pymux.conf".text = lib.mkBefore (
          header + lib.optionalString (settingLines != [ ]) ("\n" + lib.concatLines settingLines)
        );
      }

      { home.file.".pymux.conf".text = lib.mkAfter cfg.extraConfig; }
    ]
  );
}
